simulation_settings:
    group1:
        sim1:
            name: "some Simulationname"
            number_of_actors: 100
            actor_seed: 1237402
            actor_generation_method: "YES"
        sim2:
            name: " another name"
    
        defaults:
            number_of_actors: 100
            actor_seed: 1237402
            actor_generation_method: "NO"
    group2:
        sim3:
            name: "some Simulationname"
            number_of_actors: 100
            actor_seed: 1237402
            actor_generation_method: "YES"
        sim4:
            name: " another name"
    
        defaults:
            number_of_actors: 102
            actor_seed: 1237402
            actor_generation_method: "NO"
      
