simulation_settings:
    group1:
        sim1:
            sim_name: "some Simulationname"
            sim_iterations: 20
            sim_breaks: 2
            actor_complexity: 4
            actor_method: random
            graph_type: default
            graph_num_of_node: 10
            graph_init_connects: 2
            graph_branch_probability: 0.6
            graph_cluster: 1
            graph_cluster_distribution: even
            graph_cluster_methods: default

        defaults:
            sim_iterations: 20
            sim_breaks: 2
            actor_complexity: 4
            actor_method: random
            graph_type: default
            graph_num_of_node: 10
            graph_init_connects: 2
            graph_branch_probability: 0.6
            graph_cluster: 1
            graph_cluster_methods: default
            graph_cluster_distribution: even

    group2:
        sim3:
            sim_name: "some Simulationname3"
        sim4:
            sim_name: "some Simulationname4"

        defaults:
            sim_iterations: 20
            sim_breaks: 2
            actor_complexity: 4
            actor_method: random
            graph_type: default
            graph_num_of_node: 10
            graph_init_connects: 2
            graph_branch_probability: 0.6
            graph_cluster: 1
            graph_cluster_methods: default
            graph_cluster_distribution: even

      
