simulation_settings:
    group1:
        sim1:
            sim_name: "2 cluster Same opinion merging"
            sim_iterations: 20
            setup_type: "merging"
        sim2:
            sim_name: "2 cluster opposite opinions dissociating"
            sim_iterations: 40
            setup_type: "dissociating"
        sim3:
            sim_name: "clusters connected by overlay graph"
            sim_iterations: 60
            setup_type: "overlay"
            overlay_type: "Barabasi-Albert"
            overlay_initial_connections: 3
            overlay_branch_probability: 0.9

        sim4:
            sim_name: "several diverse_clusters"
            sim_iterations: 80
            setup_type: "diverse_clusters"
            subgraph_list:
              - type: "complete"
                number_of_nodes: 25
                initial_connections: 3
                probability: 0.4
                pro_likelihood: 0.7
                con_likelihood: 0.1
                consense_indexes: [0, 1]
              - type: "complete"
                number_of_nodes: 15
                initial_connections: 2
                probability: 0.6
                pro_likelihood: 0.
                con_likelihood: 0.3
                consense_indexes: [1, 2]
              - type: "complete"
                number_of_nodes: 10
                initial_connections: 2
                probability: 0.6
                pro_likelihood: 0.2
                con_likelihood: 0.1
                consense_indexes: [3]
            number_of_interconnections: 3
        sim5:
            sim_name: "default setup"
            sim_iterations: 100

        sim6:
            sim_name: "distribution to coreness"
            sim_iterations: 80
            setup_type: "coreness"
            subgraph_list:
              - type: "complete"
                number_of_nodes: 25
                initial_connections: 3
                probability: 0.4
                pro_likelihood: 0.7
                con_likelihood: 0.1
              - type: "complete"
                number_of_nodes: 15
                initial_connections: 2
                probability: 0.6
                pro_likelihood: 0.
                con_likelihood: 0.3
                consense_indexes: [1, 2]
              - type: "complete"
                number_of_nodes: 10
                initial_connections: 2
                probability: 0.6
                pro_likelihood: 0.2
                con_likelihood: 0.1
                consense_indexes: [3]
            number_of_interconnections: 3

        sim7:
            sim_name: "custom"
            sim_iterations: 80
            setup_type: "neu"
            overlay_type: "Barabasi-Albert"
            overlay_oppinion_list: [1, 1, 1, 1]
            overlay_initial_connections: 3
            overlay_branch_probability: 0.9
            subgraph_list:
              - type: "complete"
                number_of_nodes: 25
                initial_connections: 3
                probability: 0.4
                pro_likelihood: 0.7
                con_likelihood: 0.1
                consense_indexes: [3]
                oppinion_distribution_type: "equal"
              - type: "Powerlaw-Cluster"
                number_of_nodes: 15
                initial_connections: 2
                probability: 0.6
                pro_likelihood: 0.4
                con_likelihood: 0.3
                consense_indexes: [1, 2]
                oppinion_distribution_type: "equal"
              - type: "complete"
                number_of_nodes: 10
                initial_connections: 2
                probability: 0.6
                pro_likelihood: 0.2
                con_likelihood: 0.1
                fixed_oppinion_list: [3, 4, 5, 1]
                oppinion_distribution_type: "fixed"
                number_of_interconnections: 3

        defaults:
            number_of_interconnections: 0
            subgraph_list: None
            overlay_type: None
            overlay_initial_connections: None
            overlay_branch_probability: None
            setup_type: "default"
            sim_iterations: 20
            sim_breaks: 2
            actor_complexity: 4
            actor_method: random
            graph_type: default
            graph_num_of_node: 10
            graph_init_connects: 2
            graph_branch_probability: 0.6
            graph_cluster: 4
            graph_cluster_methods: default
            graph_cluster_distribution: even
            OrientationConfirmationRule:
                fallbackProbability: 0.5
            AdaptationRule:
            NewNodeRule:
                densityThreshold: 0.8
                meanOrientationThreshold: 0.8
                opMeanThreshold: 0.8
            NewEdgesRule:
                createEdgeProbability: 0.1
            RemoveEdgeRule:
                absOrientationThreshold: 0.1
            TakeoverRule:
                removalProbability: 0.5
                minDifference: 1

    group2:
        sim3:
            sim_name: "some Simulationname3"
        sim4:
            sim_name: "some Simulationname4"

        defaults:
            sim_iterations: 20
            sim_breaks: 20
            actor_complexity: 4
            actor_method: random
            graph_type: default
            graph_num_of_node: 10
            graph_init_connects: 2
            graph_branch_probability: 0.6
            graph_cluster: 2
            graph_cluster_methods: default
            graph_cluster_distribution: even
            OrientationConfirmationRule:
                fallbackProbability: 0.5
            AdaptationRule:
            NewNodeRule:
                densityThreshold: 0.8
                meanOrientationThreshold: 0.8
                opMeanThreshold: 0.8
            NewEdgesRule:
                createEdgeProbability: 0.1
            RemoveEdgeRule:
                absOrientationThreshold: 0.1
            TakeoverRule:
                removalProbability: 0.5
                minDifference: 1


      
