simulation_settings:
    group1:
        sim1:
            sim_name: "2 CLuster Same opinion 20"
            sim_iterations: 20
        sim2:
            sim_name: "2 CLuster Same opinion 20"
            sim_iterations: 40
        sim3:
            sim_name: "2 CLuster Same opinion 20"
            sim_iterations: 60
        sim4:
            sim_name: "2 CLuster Same opinion 20"
            sim_iterations: 80
        sim5:
            sim_name: "2 CLuster Same opinion 20"
            sim_iterations: 100


        defaults:
            sim_iterations: 20
            sim_breaks: 2
            actor_complexity: 4
            actor_method: random
            graph_type: default
            graph_num_of_node: 10
            graph_init_connects: 2
            graph_branch_probability: 0.6
            graph_cluster: 2
            graph_cluster_methods: default
            graph_cluster_distribution: even

    group2:
        sim3:
            sim_name: "some Simulationname3"
        sim4:
            sim_name: "some Simulationname4"

        defaults:
            sim_iterations: 20
            sim_breaks: 20
            actor_complexity: 4
            actor_method: random
            graph_type: default
            graph_num_of_node: 10
            graph_init_connects: 2
            graph_branch_probability: 0.6
            graph_cluster: 2
            graph_cluster_methods: default
            graph_cluster_distribution: even

      
